### PR TITLE
fix(robo): reload environment variables in dev mode

### LINKED ISSUE #302: patch(robo): reload environment variables in `dev` mode
Dev mode currently relies on worker threads to refresh ESM modules. While this does yield the updated code, environment variables are not updated the same way when the `.env` file is updated. The code responsible for loading these is `src/core/dotenv.ts` via a simple `loadEnv()` function, which is currently only called at the beginning of `start` and `dev` CLI commands. 

My ideal solution is as follows:
- Call `loadEnv` in `Robo.start()` the same way Flashcore is prepared.
- Ensure worker threads do not inherit environment variables, for a clean start.

### PR DESCRIPTION
**Pull request by icmedev**
This PR fixes environment variable reloading in dev mode by:
- Stop env vars from being inherited in worker threads
- Only pass needed vars (PATH, FORCE_COLOR, NODE_ENV)
- Makes .env changes work right away in dev mode

Fixes #302, #352

### CODE REVIEW

File: packages/robo/src/cli/commands/dev.ts [hunk 1]
```diff
@@ -308,7 +308,12 @@ export async function buildAsync(command: string | null, config: Config, verbose
 
 			logger.debug(`> ${pkgManager} ${args.join(' ')}`)
 			const childProcess = spawn(pkgManager, args, {
-				env: { ...process.env, FORCE_COLOR: '1' },
+				env: {
+					// Only pass through essential vars, not the entire env
```
Comment (Pkmmte) [inline packages/robo/src/cli/commands/dev.ts:312]: Mmm, I'm not sure if this is a good idea. There are several reasons why one would want environment variables to be inherited.

### Example 1: Inline variables

Sometimes people pass environment variables inline as part of a script, either as a replacement or as an addition to `.env` loading.

```json
  "dev": "NODE_ENV=test robo dev",
  "start": "NODE_ENV=prod robo start"
```

### Example 2: Doppler

This is a service I personally use a lot in organizations. Doppler replaces the need for `.env` files. Similar to example 1, it injects variables to the process expecting it to be inherited.

```json
  "dev": "doppler run -- robo dev"
```


Passing only essential variables completely breaks the above two scenarios which are commonly used.

**Review by Pkmmte — APPROVED** [review]
